(function(){'use strict';var r;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var t=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var u=ba(this);function v(a,b){if(b)a:{var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];if(!(g in c))break a;c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&t(c,a,{configurable:!0,writable:!0,value:b})}}
v("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+g++,k)}function c(k,e){this.g=k;t(this,"description",{configurable:!0,writable:!0,value:e})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",g=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=u[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&t(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function w(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function da(a){if(!(a instanceof Array)){a=w(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function x(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.va=b.prototype}function la(){this.i=!1;this.g=null;this.C=void 0;this.l=1;this.A=0;this.h=null}function ma(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}la.prototype.o=function(a){this.C=a};function na(a,b){a.h={da:b,ma:!0};a.l=a.A}
la.prototype.return=function(a){this.h={return:a};this.l=this.A};function oa(a){this.g=new la;this.h=a}function pa(a,b){ma(a.g);var c=a.g.g;if(c)return qa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return z(a)}
function qa(a,b,c,d){try{var g=b.call(a.g.g,c);if(!(g instanceof Object))throw new TypeError("Iterator result "+g+" is not an object");if(!g.done)return a.g.i=!1,g;var k=g.value}catch(e){return a.g.g=null,na(a.g,e),z(a)}a.g.g=null;d.call(a.g,k);return z(a)}function z(a){for(;a.g.l;)try{var b=a.h(a.g);if(b)return a.g.i=!1,{value:b.value,done:!1}}catch(c){a.g.C=void 0,na(a.g,c)}a.g.i=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.ma)throw b.da;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ra(a){this.next=function(b){ma(a.g);a.g.g?b=qa(a,a.g.g.next,b,a.g.o):(a.g.o(b),b=z(a));return b};this.throw=function(b){ma(a.g);a.g.g?b=qa(a,a.g.g["throw"],b,a.g.o):(na(a.g,b),b=z(a));return b};this.return=function(b){return pa(a,b)};this[Symbol.iterator]=function(){return this}}function sa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,g){function k(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(k,g)}k(a.next())})}
function ta(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
v("Promise",function(a){function b(e){this.h=0;this.i=void 0;this.g=[];this.C=!1;var f=this.l();try{e(f.resolve,f.reject)}catch(h){f.reject(h)}}function c(){this.g=null}function d(e){return e instanceof b?e:new b(function(f){f(e)})}if(a)return a;c.prototype.h=function(e){if(this.g==null){this.g=[];var f=this;this.i(function(){f.o()})}this.g.push(e)};var g=u.setTimeout;c.prototype.i=function(e){g(e,0)};c.prototype.o=function(){for(;this.g&&this.g.length;){var e=this.g;this.g=[];for(var f=0;f<e.length;++f){var h=
e[f];e[f]=null;try{h()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(e){this.i(function(){throw e;})};b.prototype.l=function(){function e(l){return function(m){h||(h=!0,l.call(f,m))}}var f=this,h=!1;return{resolve:e(this.Z),reject:e(this.o)}};b.prototype.Z=function(e){if(e===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.ba(e);else{a:switch(typeof e){case "object":var f=e!=null;break a;case "function":f=!0;break a;default:f=!1}f?this.Y(e):this.A(e)}};
b.prototype.Y=function(e){var f=void 0;try{f=e.then}catch(h){this.o(h);return}typeof f=="function"?this.ca(f,e):this.A(e)};b.prototype.o=function(e){this.U(2,e)};b.prototype.A=function(e){this.U(1,e)};b.prototype.U=function(e,f){if(this.h!=0)throw Error("Cannot settle("+e+", "+f+"): Promise already settled in state"+this.h);this.h=e;this.i=f;this.h===2&&this.aa();this.ta()};b.prototype.aa=function(){var e=this;g(function(){if(e.ua()){var f=u.console;typeof f!=="undefined"&&f.error(e.i)}},1)};b.prototype.ua=
function(){if(this.C)return!1;var e=u.CustomEvent,f=u.Event,h=u.dispatchEvent;if(typeof h==="undefined")return!0;typeof e==="function"?e=new e("unhandledrejection",{cancelable:!0}):typeof f==="function"?e=new f("unhandledrejection",{cancelable:!0}):(e=u.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.i;return h(e)};b.prototype.ta=function(){if(this.g!=null){for(var e=0;e<this.g.length;++e)k.h(this.g[e]);this.g=null}};var k=new c;b.prototype.ba=
function(e){var f=this.l();e.D(f.resolve,f.reject)};b.prototype.ca=function(e,f){var h=this.l();try{e.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};b.prototype.then=function(e,f){function h(n,p){return typeof n=="function"?function(y){try{l(n(y))}catch(E){m(E)}}:p}var l,m,q=new b(function(n,p){l=n;m=p});this.D(h(e,l),h(f,m));return q};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.D=function(e,f){function h(){switch(l.h){case 1:e(l.i);break;case 2:f(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?k.h(h):this.g.push(h);this.C=!0};b.resolve=d;b.reject=function(e){return new b(function(f,h){h(e)})};b.race=function(e){return new b(function(f,h){for(var l=w(e),m=l.next();!m.done;m=l.next())d(m.value).D(f,h)})};b.all=function(e){var f=w(e),h=f.next();return h.done?d([]):new b(function(l,m){function q(y){return function(E){n[y]=E;p--;p==0&&l(n)}}var n=[],p=0;do n.push(void 0),p++,d(h.value).D(q(n.length-1),m),h=f.next();while(!h.done)})};return b});
function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}v("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
v("WeakMap",function(a){function b(h){this.g=(f+=Math.random()+1).toString();if(h){h=w(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function g(h){if(!A(h,e)){var l=new c;t(h,e,{value:l})}}function k(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&g(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(q){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var f=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");g(h);if(!A(h,e))throw Error("WeakMap key fail: "+h);h[e][this.g]=l;return this};b.prototype.get=function(h){return d(h)&&A(h,e)?h[e][this.g]:void 0};b.prototype.has=function(h){return d(h)&&A(h,
e)&&A(h[e],this.g)};b.prototype.delete=function(h){return d(h)&&A(h,e)&&A(h[e],this.g)?delete h[e][this.g]:!1};return b});
v("Map",function(a){function b(){var f={};return f.v=f.next=f.head=f}function c(f,h){var l=f[1];return ca(function(){if(l){for(;l.head!=f[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(f,h){var l=h&&typeof h;l=="object"||l=="function"?k.has(h)?l=k.get(h):(l=""+ ++e,k.set(h,l)):l="p_"+h;var m=f[0][l];if(m&&A(f[0],l))for(f=0;f<m.length;f++){var q=m[f];if(h!==h&&q.key!==q.key||h===q.key)return{id:l,list:m,index:f,s:q}}return{id:l,
list:m,index:-1,s:void 0}}function g(f){this[0]={};this[1]=b();this.size=0;if(f){f=w(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var f=Object.seal({x:4}),h=new a(w([[f,"s"]]));if(h.get(f)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=f||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(q){return!1}}())return a;var k=new WeakMap;g.prototype.set=function(f,h){f=f===0?0:f;var l=d(this,f);l.list||(l.list=this[0][l.id]=[]);l.s?l.s.value=h:(l.s={next:this[1],v:this[1].v,head:this[1],key:f,value:h},l.list.push(l.s),this[1].v.next=l.s,this[1].v=l.s,this.size++);return this};g.prototype.delete=function(f){f=d(this,f);return f.s&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.s.v.next=f.s.next,f.s.next.v=f.s.v,f.s.head=
null,this.size--,!0):!1};g.prototype.clear=function(){this[0]={};this[1]=this[1].v=b();this.size=0};g.prototype.has=function(f){return!!d(this,f).s};g.prototype.get=function(f){return(f=d(this,f).s)&&f.value};g.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};g.prototype.keys=function(){return c(this,function(f){return f.key})};g.prototype.values=function(){return c(this,function(f){return f.value})};g.prototype.forEach=function(f,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,f.call(h,m[1],m[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var e=0;return g});
v("Set",function(a){function b(c){this.g=new Map;if(c){c=w(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(w([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var g=d.entries(),k=g.next();if(k.done||k.value[0]!=c||k.value[1]!=c)return!1;k=g.next();return k.done||k.value[0]==c||k.value[0].x!=4||
k.value[1]!=k.value[0]?!1:g.next().done}catch(e){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var g=this;this.g.forEach(function(k){return c.call(d,k,k,g)})};return b});v("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push(b[d]);return c}});v("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
v("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var g=d.length;c=c||0;for(c<0&&(c=Math.max(c+g,0));c<g;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});
v("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
v("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(f){return f};var g=[],k=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof k=="function"){b=k.call(b);for(var e=0;!(k=b.next()).done;)g.push(c.call(d,k.value,e++))}else for(k=b.length,e=0;e<k;e++)g.push(c.call(d,b[e],e));return g}});v("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});v("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
v("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});v("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});function ua(a,b){a instanceof String&&(a+="");var c=0,d=!1,g={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};g[Symbol.iterator]=function(){return g};return g}v("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});
v("Array.prototype.keys",function(a){return a?a:function(){return ua(this,function(b){return b})}});v("Array.prototype.values",function(a){return a?a:function(){return ua(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var B=this||self;function va(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=B,g=0;g<c.length;g++)if(d=d[c[g]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function wa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};function xa(a){B.setTimeout(function(){throw a;},0)};var ya=va(610401301,!1),za=va(653718497,va(1,!0));var C,Aa=B.navigator;C=Aa?Aa.userAgentData||null:null;function Ba(a){return ya?C?C.brands.some(function(b){return(b=b.brand)&&b.indexOf(a)!=-1}):!1:!1}function D(a){var b;a:{if(b=B.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};function F(){return ya?!!C&&C.brands.length>0:!1}function Ca(){return F()?Ba("Chromium"):(D("Chrome")||D("CriOS"))&&!(F()?0:D("Edge"))||D("Silk")};var Da=F()?!1:D("Trident")||D("MSIE");!D("Android")||Ca();Ca();D("Safari")&&(Ca()||(F()?0:D("Coast"))||(F()?0:D("Opera"))||(F()?0:D("Edge"))||(F()?Ba("Microsoft Edge"):D("Edg/"))||F()&&Ba("Opera"));var Ea={},G=null;var Fa=typeof Uint8Array!=="undefined",Ga=!Da&&typeof btoa==="function";function Ha(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function Ia(){var a=Error();Ha(a,"incident");xa(a)};var H=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Ja(a){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?Symbol():a}var Ka=Ja(),J=Ja("1oa");var K=H?function(a){return a[Ka]|0}:function(a){return a.H|0},L=H?function(a){return a[Ka]}:function(a){return a.H},La=H?function(a,b){a[Ka]=b}:function(a,b){a.H!==void 0?a.H=b:Object.defineProperties(a,{H:{value:b,configurable:!0,writable:!0,enumerable:!1}})};var Ma={},Na={};function Oa(a){return!(!a||typeof a!=="object"||a.g!==Na)}function M(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)&&a.constructor===Object}function N(a){return!Array.isArray(a)||a.length?!1:K(a)&1?!0:!1}function Pa(a){if(a&2)throw Error();}Object.freeze({});var Qa=Object.freeze({});var Ra=typeof B.BigInt==="function"&&typeof B.BigInt(0)==="bigint";var Sa=Number.MIN_SAFE_INTEGER.toString(),Ta=Ra?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ua=Number.MAX_SAFE_INTEGER.toString(),Va=Ra?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Wa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],g=b[c];if(d>g)return!1;if(d<g)return!0}};var O=void 0;function Xa(a,b){var c=Ya(a,b);c&&!Za(a,c)&&($a(),ab(a,b))}function Za(a,b){if(a.length!==b.length)return!1;for(var c in b){var d=Number(c),g;if(g=Number.isInteger(d))g=a[d],d=b[d],g=!(Number.isNaN(g)?Number.isNaN(d):g===d);if(g)return!1}return!0}function $a(){Ia()}var P=void 0;function Ya(a,b){var c,d;return(c=P)==null?void 0:(d=c.get(b))==null?void 0:d.get(a)}function ab(a,b){var c,d;(c=P)==null||(d=c.get(b))==null||d.delete(a)};var bb;
function Q(a,b,c){a==null&&(a=bb);bb=void 0;if(a==null){var d=96;c?(a=[c],d|=512):a=[];b&&(d=d&-33521665|(b&1023)<<15)}else{if(!Array.isArray(a))throw Error("narr");d=K(a);if(d&2048)throw Error("farr");if(d&64)return a;d|=64;if(c&&(d|=512,c!==a[0]))throw Error("mid");a:{c=a;var g=c.length;if(g){var k=g-1;if(M(c[k])){d|=256;b=k-(+!!(d&512)-1);if(b>=1024)throw Error("pvtlmt");d=d&-33521665|(b&1023)<<15;break a}}if(b){b=Math.max(b,g-(+!!(d&512)-1));if(b>1024)throw Error("spvt");d=d&-33521665|(b&1023)<<
15}}}La(a,d);return a};function cb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "bigint":return(Ra?a>=Ta&&a<=Va:a[0]==="-"?Wa(a,Sa):Wa(a,Ua))?Number(a):String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(N(a))return}else if(Fa&&a!=null&&a instanceof Uint8Array){if(Ga){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{b===void 0&&(b=0);if(!G){G={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");
d=["+/=","+/","-_=","-_.","-_"];for(var g=0;g<5;g++){var k=c.concat(d[g].split(""));Ea[g]=k;for(var e=0;e<k.length;e++){var f=k[e];G[f]===void 0&&(G[f]=e)}}}b=Ea[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=k=0;k<a.length-2;k+=3){var h=a[k],l=a[k+1];f=a[k+2];e=b[h>>2];h=b[(h&3)<<4|l>>4];l=b[(l&15)<<2|f>>6];f=b[f&63];c[g++]=e+h+l+f}e=0;f=d;switch(a.length-k){case 2:e=a[k+1],f=b[(e&15)<<2]||d;case 1:a=a[k],c[g]=b[a>>2]+b[(a&3)<<4|e>>4]+f+d}a=c.join("")}return a}}return a};function db(a,b,c,d,g){if(a!=null){if(Array.isArray(a))a=N(a)?void 0:g&&K(a)&2?a:eb(a,b,c,d!==void 0,g);else if(M(a)){var k={},e;for(e in a)k[e]=db(a[e],b,c,d,g);a=k}else a=b(a,d);return a}}function eb(a,b,c,d,g){var k=d||c?K(a):0;d=d?!!(k&32):void 0;a=Array.prototype.slice.call(a);for(var e=0;e<a.length;e++)a[e]=db(a[e],b,c,d,g);c&&c(k,a);return a}function fb(a){return a.S===Ma?a.toJSON():Fa&&a!=null&&a instanceof Uint8Array?new Uint8Array(a):a}function gb(a){return a.S===Ma?a.toJSON():cb(a)};function R(a,b,c,d){var g=b>>15&1023||536870912;if(c>=g){var k=b;if(b&256)var e=a[a.length-1];else{if(d==null)return k;e=a[g+(+!!(b&512)-1)]={};k|=256}e[c]=d;c<g&&(a[c+(+!!(b&512)-1)]=void 0);k!==b&&La(a,k);return k}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}function hb(a,b){a=a.m;return ib(jb(a),a,L(a),b)}function jb(a){if(H){var b;return(b=a[J])!=null?b:a[J]=new Map}if(J in a)return a[J];b=new Map;Object.defineProperty(a,J,{value:b});return b}
function ib(a,b,c,d){var g=a.get(d);if(g!=null)return g;for(var k=g=0;k<d.length;k++){var e=d[k];var f=b;var h=c;if(e===-1)f=null;else{var l=h>>15&1023||536870912;e>=l?f=h&256?f[f.length-1][e]:void 0:(h=e+(+!!(h&512)-1),f=h<0||h>=f.length||h>=l?void 0:f[h])}f!=null&&(g!==0&&(c=R(b,c,g)),g=e)}a.set(d,g);return g}
function S(a,b,c){var d=kb;c==null&&(c=void 0);a:{var g=a.m,k=L(g);Pa(k);if(c==null){var e=jb(g);if(ib(e,g,k,d)===b)e.set(d,0);else break a}else{e=jb(g);var f=ib(e,g,k,d);f!==b&&(f&&(k=R(g,k,f)),e.set(d,b))}R(g,k,b,c)}return a}function lb(a,b){a=2&b?a|2:a&-3;return(a|32)&-2049}function mb(a,b){32&b||(a&=-33);return a}function nb(a,b,c){if(c!=null&&typeof c!=="string")throw Error();var d=a.m,g=L(d);Pa(g);R(d,g,b,c);return a};var T,ob;function U(a,b,c){this.m=Q(a,b,c)}U.prototype.toJSON=function(){return pb(this)};U.prototype.S=Ma;U.prototype.toString=function(){try{return T=!0,pb(this).toString()}finally{T=!1}};
function pb(a){var b;if(a&&(b=P)!=null&&b.has(a)&&(b=a.m))for(var c=0;c<b.length;c++){var d=b[c];if(c===b.length-1&&M(d))for(var g in d){var k=d[g];Array.isArray(k)&&Xa(k,a)}else Array.isArray(d)&&Xa(d,a)}a=T?a.m:ob?eb(a.m,fb,void 0,void 0,!1):eb(a.m,gb,void 0,void 0,!1);g=!T;if(b=a.length){d=a[b-1];(k=M(d))?b--:d=void 0;c=a;if(k){b:{var e=d;var f;var h=!1;if(e)for(var l in e)if(isNaN(+l))k=void 0,((k=f)!=null?k:f={})[l]=e[l];else if(k=e[l],Array.isArray(k)&&(N(k)||Oa(k)&&k.size===0)&&(k=null),k==
null&&(h=!0),k!=null){var m=void 0;((m=f)!=null?m:f={})[l]=k}h||(f=e);if(f)for(var q in f){h=f;break b}h=null}e=h==null?d!=null:h!==d}for(;b>0;b--){f=c[b-1];if(!(f==null||N(f)||Oa(f)&&f.size===0))break;var n=!0}if(c!==a||e||n){if(!g)c=Array.prototype.slice.call(c,0,b);else if(n||e||h)c.length=b;h&&c.push(h)}n=c}else n=a;return n};function qb(a){this.m=Q(a)}x(qb,U);function rb(a){this.m=Q(a)}x(rb,U);function sb(a){this.m=Q(a)}x(sb,U);function tb(a){this.m=Q(a)}x(tb,U);function ub(a){this.m=Q(a)}x(ub,U);function vb(a){this.m=Q(a)}x(vb,U);function wb(a){this.m=Q(a)}x(wb,U);function xb(a){this.m=Q(a)}x(xb,U);function yb(a){this.m=Q(a)}x(yb,U);function V(a){this.m=Q(a)}x(V,U);V.prototype.G=function(){return hb(this,kb)};var kb=[1,2,3,4,5,6,7,8,9,10,11];function zb(a){this.m=Q(a)}x(zb,U);zb.prototype.G=function(){return hb(this,Ab)};var Ab=[2,3,4,5,6,7,8,9,10,11,12,13];function Bb(){}Bb.prototype.N=function(){};function Cb(a){a.indexOf("#")===0&&(a=a.substring(1));return new URLSearchParams(a)};var Db={J:!1,I:!1,requestNonPersonalizedAds:!1,P:!1,R:!1,T:!1},Eb={X:!1};function Fb(a){return a?"on":"off"}var Gb=["preroll","start","pause","next","browse"];
function Ib(a,b,c,d){var g=this;this.j=a;this.u=b;this.V=c;this.W=!1;this.L=function(k){(g.u.J||g.u.I)&&window.adsbygoogle.push({sound:Fb(k.isAudioEnabled)})};this.O=b.T?new Bb:new Jb;this.j.B("SET_AUDIO",this.L);(a=Kb.la())&&setTimeout(function(){return void Lb(g)},Math.max(0,a-Date.now()));this.j.B("SPLASH_TIMEOUT",function(){g.W=!0});window.adsbygoogle=window.adsbygoogle||[];b.requestNonPersonalizedAds&&(window.adsbygoogle.requestNonPersonalizedAds=1);if(b.J||b.I)b={preloadAdBreaks:"on",sound:Fb(d.audio.isEnabled()),
onReady:function(){window.adsbygoogle.push({preloadAdBreaks:"on"})}},window.adsbygoogle.push(b)}function Lb(a){a.W||a.break({type:"preroll",beforeAd:function(){a.V(!0);setTimeout(function(){a.j.send({messageType:"PREROLL_READY"})},33)},adBreakDone:function(){a.V(!1);a.j.send({messageType:"PREROLL_DONE"})}})}
Ib.prototype.break=function(a){var b=this;this.j.send({messageType:"AD_BREAK"});if(a.type!=="preroll"){var c=a.beforeAd;a.beforeAd=function(){b.j.send({messageType:"BEFORE_AD"});c==null||c()};var d=a.afterAd;a.afterAd=function(){b.j.send({messageType:"AFTER_AD"});d==null||d()}}this.u.J&&a.type==="reward"&&this.O.N(a);this.u.I&&Gb.includes(a.type)&&this.O.N(a)};var Kb={la:function(a){a=Cb(a||window.location.hash);if(!a)return 0;a=(a=a.get("preStart"))?Number(a):0;return isNaN(a)?0:a}};
function Jb(){}Jb.prototype.N=function(a){window.adsbygoogle.push(a)};function Mb(){};function W(a){var b=this;this.j=a;this.g=!Nb.ea();this.o=[];this.h=!1;this.i=!0;this.A=this.g;this.L=function(c){b.g=c.isAudioEnabled;Ob(b)};this.j.B("SET_AUDIO",this.L)}W.prototype.l=function(a){this.h!==a&&(this.h=a,Ob(this))};function Ob(a){var b=a.g&&!a.h&&a.i;if(b!==a.A){for(var c=w(a.o),d=c.next();!d.done;d=c.next())d=d.value,d(b);a.A=b}}W.prototype.isEnabled=function(){this.j.send({messageType:"AUDIO_IS_ENABLED"});return this.g&&!this.h&&this.i};
W.prototype.subscribe=function(a){typeof a==="function"&&(this.j.send({messageType:"AUDIO_SUBSCRIBE"}),this.o.push(a))};var Nb={ea:function(a){return Cb(a||window.location.hash).get("audioMuted")==="true"}};function Pb(a){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack)}x(Pb,Error);function Qb(a,b){this.data=a;this.channel=b};function Rb(a){this.g=a}Rb.prototype.send=function(a,b,c){c=c===void 0?[]:c;b=Sb(b);this.g.postMessage(a,[b.port2].concat(c))};function Tb(a,b){Ub(a,b);return new Rb(a)}function Sb(a){var b=new MessageChannel;Ub(b.port1,a);return b}function Ub(a,b){b&&(a.onmessage=function(c){var d=c.data;c=Tb(c.ports[0]);b(new Qb(d,c))})};function Vb(a){try{a()}catch(b){xa(b)}};function Wb(a){var b=this;var c=a.ja;var d=a.ra===void 0?function(){}:a.ra;var g=a.oa===void 0?function(){}:a.oa;a=a.na===void 0?function(){}:a.na;this.g=new Map;this.h=c;this.o=d;this.l=g;this.i=a;this.onMessage=function(k){return Xb(b,k)}}Wb.prototype.register=function(a,b){this.g.set(a,b);return this};function Xb(a,b){var c=a.h(b.data),d=a.g.get(c);d?(Vb(function(){return a.l(b,c)}),Vb(function(){return d(b)}),Vb(function(){return a.i(b,c)})):Vb(function(){return a.o(b,c)})};function Yb(a){this.g=a}Yb.prototype.send=function(a,b,c){var d=this.g,g=d.send;try{ob=!0;var k=pb(a)}finally{ob=!1}g.call(d,k,b,c)};function Zb(a,b){return function(c){var d=new a(c.data);return b(new Qb(d,c.channel))}}function $b(a){return function(b){return a(new Qb(b.data,new Yb(b.channel)))}};function ac(a,b,c,d){this.l=a;this.i=b;this.M=c;this.K=d;this.g=!1;this.h=new Set}
function bc(a){var b=new Wb({ja:a.G}),c={destination:window.parent,origin:a.origin,F:a.F,onMessage:$b(Zb(a.M,b.onMessage))};var d=c.destination;var g=c.origin;var k=c.sa===void 0?void 0:c.sa;var e=c.F===void 0?"ZNWN1d":c.F;c=c.onMessage===void 0?void 0:c.onMessage;if(g==="*")throw Error("Sending to wildcard origin not allowed.");var f=Sb(c),h={};k=k?(h.n=e,h.t=k,h):e;d.postMessage(k,g,[f.port2]);d=Tb(f.port1,c);return new ac(b,new Yb(d),a.M,a.K)}
ac.prototype.send=function(a){if(!this.g)throw new Pb("Attempted to send a message before initialisation.");this.i.send(a)};
ac.prototype.init=function(){var a=this;return sa(new ra(new oa(function(b){if(a.g)throw new Pb("Attempted to initialise twice. The SDK can only be initialised once.");if(a.K!==void 0){var c=a.i,d=c.send,g=a.K,k=new yb;var e=[].concat(da(a.h)),f=k.m,h=L(f);Pa(h);if(e==null)R(f,h,1);else{var l=K(e),m=l,q=!!(2&l)||Object.isFrozen(e),n;if(n=!q)n=void 0===Qa||!1;if(!(4&l)){l=21;q&&(e=Array.prototype.slice.call(e),m=0,l=lb(l,h),l=mb(l,h));for(var p=0;p<e.length;p++){var y=e,E=p,Hb=e[p];if(!Number.isFinite(Hb))throw b=
Error("enum"),Ha(b,"warning"),b;y[E]=Hb|0}}if(n)e=Array.prototype.slice.call(e),m=0,l=lb(l,h),l=mb(l,h);else if(!q){q=e;if(n=za){if(O===void 0){if(typeof WeakMap==="function"){n=WeakMap;try{var I=n.toString().indexOf("[native code]")!==-1?n:null}catch(Hc){I=null}}else I=null;O=I}n=O}if(n&&(Ya(q,k)||!(Math.random()>.01))){n=q.length;I={length:n};for(p=0;p<Math.min(n,10);p++)n<=10?y=p:(y=n/10,E=Math.floor(p*y),y=E+Math.floor(Math.random()*(Math.floor((p+1)*y)-E))),I[y]=q[y];Za(q,I)?(n=P||(P=new O),
p=n.get(k),p||(p=new O,n.set(k,p)),p.set(q,I)):(Ia(),ab(q,k))}}l!==m&&La(e,l);R(f,h,1,e)}d.call(c,g.call(a,k))}a.g=!0;b.l=0})))};function cc(a,b){if(a.g)throw new Pb("Attempted to use a new API after initialisation. All APIs must be set up before initialising the SDK.");a.h.add(b);return a.l};function dc(a){return bc({origin:a,F:"gamesnacks-developer",M:zb,G:function(b){return b.G()}})};function ec(a,b,c,d,g){this.j=a;this.channel=b===void 0?null:b;this.u=c;this.g=d;this.ad=g;this.h=[];this.i=[];this.channel!==null&&cc(this.channel,2).register(6,this.pa.bind(this)).register(7,this.qa.bind(this))}r=ec.prototype;r.firstFrameReady=function(){var a;if((a=this.channel)!=null){var b=a.send;var c=new V;var d=new qb;c=S(c,5,d);b.call(a,c)}};r.ready=function(){this.j.send({messageType:"GAME_READY",timestamp:Date.now()})};
r.onPause=function(a){this.h.push(a);if((a=this.channel)!=null){var b=a.send;var c=new V;var d=new rb;c=S(c,8,d);b.call(a,c)}};r.onResume=function(a){this.i.push(a);if((a=this.channel)!=null){var b=a.send;var c=new V;var d=new tb;c=S(c,9,d);b.call(a,c)}};r.gameOver=function(){this.j.send({messageType:"GAME_OVER"});this.u.P&&fc(this,"gameOver")};r.levelComplete=function(a){typeof a==="number"&&(this.j.send({messageType:"LEVEL_COMPLETE",level:a}),this.u.R&&fc(this,"levelComplete"))};
r.pa=function(a){for(var b=w(this.h),c=b.next();!c.done;c=b.next())c=c.value,c();b=new V;c=new sb;b=S(b,6,c);a.channel.send(b,void 0,void 0)};r.qa=function(a){for(var b=w(this.i),c=b.next();!c.done;c=b.next())c=c.value,c();b=new V;c=new ub;b=S(b,7,c);a.channel.send(b,void 0,void 0)};function fc(a,b){a.ad.break({type:"next",name:b,beforeAd:function(){return void a.g.l(!0)},afterAd:function(){return void a.g.l(!1)}})};function gc(a){a&&typeof a.dispose=="function"&&a.dispose()};function X(){this.h=this.h;this.g=this.g}X.prototype.h=!1;X.prototype.dispose=function(){if(!this.h&&(this.h=!0,this.g))for(;this.g.length;)this.g.shift()()};X.prototype[Symbol.dispose]=function(){this.dispose()};function Y(a,b){a.h?b():(a.g||(a.g=[]),a.g.push(b))};function hc(a){X.call(this);var b=this;this.audio=a;this.i=function(){var c=b.audio,d=!document.hidden;c.i!==d&&(c.i=d,Ob(c))};Y(this,function(){document.removeEventListener("visibilitychange",b.i,!1)});document.addEventListener("visibilitychange",this.i,!1)}x(hc,X);function ic(a){this.j=a}ic.prototype.update=function(a){typeof a==="number"&&this.j.send({messageType:"SCORE",score:a})};function jc(a){return a[B.Symbol.iterator]()}function kc(a,b){this.g=jc(a);this.h=b}kc.prototype[Symbol.iterator]=function(){return this};kc.prototype.next=function(){var a=this.g.next();return{value:a.done?void 0:this.h.call(void 0,a.value),done:a.done}};function lc(a,b){return new kc(a,b)}function mc(a){this.h=a;this.g=0}mc.prototype[Symbol.iterator]=function(){return this};mc.prototype.next=function(){for(;this.g<this.h.length;){var a=this.h[this.g].next();if(!a.done)return a;this.g++}return{done:!0}};
function nc(){return new mc(ta.apply(0,arguments).map(jc))};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function oc(a){this.g=a}oc.prototype.toString=function(){return this.g};var pc=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function qc(a,b){if(b instanceof oc)if(b instanceof oc)b=b.g;else throw Error("");else b=pc.test(b)?b:void 0;b!==void 0&&(a.href=b)};function rc(){var a=document;var b="A";a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)};var sc=B.URL,tc;try{new sc("http://example.com"),tc=!0}catch(a){tc=!1}var uc=tc;function Z(a){this.g=new Map;a.indexOf("?")==0&&(a=a.substring(1));a=w(a.split("&"));for(var b=a.next();!b.done;b=a.next()){var c=b.value;b=c;var d="";c=c.split("=");c.length>1&&(b=decodeURIComponent(c[0].replace("+"," ")),d=decodeURIComponent(c[1].replace("+"," ")));c=this.g.get(b);c==null&&(c=[],this.g.set(b,c));c.push(d)}}Z.prototype.get=function(a){return(a=this.g.get(a))&&a.length?a[0]:null};
Z.prototype.getAll=function(a){return[].concat(da(this.g.get(a)||[]))};Z.prototype.has=function(a){return this.g.has(a)};Z.prototype[Symbol.iterator]=function(){return nc.apply(null,da(lc(this.g,function(a){var b=a[0];return lc(a[1],function(c){return[b,c]})})))};Z.prototype.toString=function(){return vc(this)};
function vc(a){function b(c){return encodeURIComponent(c).replace(/[!()~']|(%20)/g,function(d){return{"!":"%21","(":"%28",")":"%29","%20":"+","'":"%27","~":"%7E"}[d]})}return Array.from(a,function(c){return b(c[0])+"="+b(c[1])}).join("&")}
function wc(a){var b=rc();try{qc(b,new oc(a));var c=b.protocol}catch(g){throw Error(a+" is not a valid URL.");}if(c===""||c===":"||c[c.length-1]!=":")throw Error(a+" is not a valid URL.");if(!xc.has(c))throw Error(a+" is not a valid URL.");if(!b.hostname)throw Error(a+" is not a valid URL.");var d=b.href;a={href:d,protocol:b.protocol,username:"",password:"",hostname:b.hostname,pathname:"/"+b.pathname,search:b.search,hash:b.hash,toString:function(){return d}};xc.get(b.protocol)===b.port?(a.host=a.hostname,
a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=b.host,a.port=b.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a}var xc=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);var yc={google_ama_config:!0};function zc(a){this.channel=a===void 0?null:a;this.g={};if(a=Ac.ia()||Ac.ha())try{var b=JSON.parse(atob(decodeURIComponent(a)));if(typeof b!=="object")throw Error("malformed gameData param: "+a);this.g=b}catch(c){console.error("Error parsing gameData param: "+JSON.stringify(c))}}r=zc.prototype;r.clear=function(){var a=new V;var b=new vb;a=S(a,4,b);var c;(c=this.channel)==null||c.send(a);this.g={}};r.getItem=function(a){var b;return(b=this.g[a])!=null?b:null};
r.setItem=function(a,b){["boolean","number"].includes(typeof b)&&(b=b.toString());if(!yc[a]){var c=new V;var d=new xb;d=nb(d,1,a);d=nb(d,2,b);c=S(c,1,d);var g;(g=this.channel)==null||g.send(c);this.g[a]=b}};r.removeItem=function(a){var b=new V;var c=new wb;c=nb(c,1,a);b=S(b,3,c);var d;(d=this.channel)==null||d.send(b);delete this.g[a]};r.key=function(a){var b=Object.keys(this.g);return a>=b.length?null:b[a]};r.hasOwnProperty=function(a){return this.g.hasOwnProperty(a)};
u.Object.defineProperties(zc.prototype,{length:{configurable:!0,enumerable:!0,get:function(){var a;return(a=Object.keys(this.g).length)!=null?a:0}}});
var Ac={ha:function(){var a=window.location.href;if(uc){try{var b=new sc(a)}catch(d){throw Error(a+" is not a valid URL.");}var c=xc.get(b.protocol);if(!c)throw Error(a+" is not a valid URL.");if(!b.hostname)throw Error(a+" is not a valid URL.");b.origin=="null"&&(a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash},a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port,
b=a)}else b=wc(a);return(uc&&b.searchParams?b.searchParams:new Z(b.search)).get("gameData")},ia:function(a){a=a||window.location.hash;return Cb(a).get("gameData")}};function Bc(a,b,c,d,g){b=b===void 0?null:b;c=c===void 0?Db:c;X.call(this);this.j=a;this.channel=b;this.u=c;this.i=g;this.audio=new W(this.j);this.ad=new Ib(this.j,this.u,this.audio.l.bind(this.audio),this);this.game=new ec(this.j,this.channel,this.u,this.audio,this.ad);this.score=new ic(this.j);this.storage=new zc(this.channel);this.j.send({messageType:"LOADED"});a.B("SET_LOG_LEVEL",Mb);this.l=new hc(this.audio);Y(this,wa(gc,this.l));Y(this,wa(gc,a));this.i&&Y(this,wa(gc,this.i));b&&(cc(b,4),b.init())}
x(Bc,X);function Cc(){X.apply(this,arguments);this.targetOrigin=""}x(Cc,X);Cc.prototype.B=function(){};Cc.prototype.send=function(){};function Dc(a){X.call(this);var b=this;this.targetOrigin=a;this.i=new Map;if(a==="*")throw Error("targetOrigin of '*' is insecure. Use the origin of the parent frame.");Y(this,function(){b.i.clear()});window.addEventListener("message",function(c){var d=c.data;if(c.origin===b.targetOrigin&&typeof(d==null?void 0:d.messageType)==="string"&&(c=d.messageType,typeof d!=="object"||d===null?0:d.messageType===c)&&(c=b.i.get(c))){c=w(c);for(var g=c.next();!g.done;g=c.next())g=g.value,g(d)}})}x(Dc,X);
Dc.prototype.B=function(a,b){if(!this.h){var c=this.i.get(a);c||(c=new Set,this.i.set(a,c));c.add(b)}};Dc.prototype.send=function(a){window.parent.postMessage(a,this.targetOrigin)};function Ec(a,b){X.call(this);var c=this;this.j=a;this.window=b;this.i=this.userActivityLoggingIntervalMs=0;this.o=function(d){d=d.userActivityLoggingIntervalMs;d<=0||(c.userActivityLoggingIntervalMs=d,c.window.addEventListener("pointerdown",c.l,!0))};this.l=function(d){!d.isTrusted||Date.now()-c.i<c.userActivityLoggingIntervalMs||(c.i=Date.now(),c.j.send({messageType:"USER_ACTIVITY"}))};a.B("SET_USER_ACTIVITY_METRICS_INTERVAL",this.o)}x(Ec,X);
Ec.prototype.dispose=function(){X.prototype.dispose.call(this);this.window.removeEventListener("pointerdown",this.l,!0)};var Fc={fa:function(){var a;return((a=document.currentScript)==null?void 0:a.getAttribute("data-target-origin"))||void 0},ka:function(a){return document.currentScript?{J:document.currentScript.hasAttribute("data-rewarded-monetizable"),I:document.currentScript.hasAttribute("data-interstitial-monetizable"),requestNonPersonalizedAds:document.currentScript.hasAttribute("data-request-non-personalized-ads"),P:a&&document.currentScript.hasAttribute("data-game-over-monetizable"),R:a&&document.currentScript.hasAttribute("data-level-complete-monetizable"),
T:document.currentScript.hasAttribute("data-run-slotcar-ads-in-game-center")}:Db},ga:function(){return document.currentScript?{X:document.currentScript.hasAttribute("data-user-activity-metrics")}:Eb}};function Gc(){try{document.body&&document.body.style&&(document.body.style.userSelect="none",document.body.style.webkitUserSelect="none")}catch(a){console.warn(a)}};(function(a){a=a===void 0?!0:a;var b=Fc.fa(),c=null;if(b===null||b===void 0){console.warn("Couldn't find targetOrigin for postMessages. Cross-frame messaging is deactivated.");var d=new Cc}else d=new Dc(b),c=dc(b);b=Fc.ga();a=new Bc(d,c,Fc.ka(a),b,b.X?new Ec(d,window):void 0);window.GameSnacks=a;Object.defineProperty(window,"localStorage",{get:function(){throw Error("window.localStorage not available, please use the GameSnacks.storage API.");}});window.addEventListener("load",function(){Gc()});Gc();
return a})();}).call(this);
/*h5games_sdks_20240920-11_RC00*/